# Generated by Django 5.0.1 on 2024-02-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='change_date',
            field=models.DateField(),
        ),
    ]
