# Generated by Django 5.0.1 on 2024-02-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authorapp', '0002_alter_commentmodel_change_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='change_date',
            field=models.DateField(auto_now=True),
        ),
    ]
