# Generated by Django 5.0.1 on 2024-02-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headsandtailsmodel',
            name='side',
            field=models.CharField(default='Heads', max_length=10),
        ),
    ]
