# Generated by Django 5.0.1 on 2024-02-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my1app', '0002_alter_headsandtailsmodel_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headsandtailsmodel',
            name='side',
            field=models.CharField(default='Tails', max_length=10),
        ),
    ]
